# Generated by Django 5.2.16 on 2026-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('attendance', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, verbose_name='Придет')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('wish', models.TextField(blank=True, verbose_name='Пожелание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
    ]
