# Generated by Django 5.2.16 on 2026-07-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeguest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
