# Generated by Django 5.2.16 on 2026-07-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeguest', '0002_guest_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='extra_guests',
            field=models.TextField(blank=True, verbose_name='Добавленные гости'),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Всего гостей'),
        ),
    ]
